# This is a basic workflow to help you get started with Actions
name: TEST
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: WebPageTest
        uses: catchpoint/WebPageTest.github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: https://www.google.com/
          label: 'GitHub Action Test'
